service: cluster

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2
  memorySize: 3008

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'